{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.chartname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}
{{- end }}