{{- if .Values.config.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.chartname" . }}-admin-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.config.admin.password | quote }}
{{- end }}
{{- if .Values.config.admin.jwtSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.chartname" . }}-admin-jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.config.admin.jwtSecretKey | quote }}
{{- end }}